profile:
  username: "@4n00bs"
  image: "profile.jpg"

links:
  - category: "Telegram"
    links_list:
      - name: "Telegram - android4noobs"
        url: "https://t.me/android4noobs"
        image: "profile.jpg"
      - name: "Telegram - python4noobs"
        url: "https://t.me/python4noobs"
        image: "profile.jpg"
  - category: "Threads"
    links_list:
      - name: "Threads - android4noobs"
        url: "https://threads.net/android4noobs"
        image: "profile.jpg"
      - name: "Threads - python4noobs"
        url: "https://threads.net/python4noobs"
        image: "profile.jpg"
  - category: "X"
    links_list:
      - name: "X - android4noobs"
        url: "https://twitter.com/android4noobs"
        image: "profile.jpg"
      - name: "X - python4noobs"
        url: "https://twitter.com/python4noobs"
        image: "profile.jpg"