name: Generate and Deploy Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Replace environment variables in HTML
      run: |
        sed -i 's|FIREBASE_API_KEY|${{ secrets.FIREBASE_API_KEY }}|g' templates/index.html
        sed -i 's|FIREBASE_AUTH_DOMAIN|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g' templates/index.html
        sed -i 's|FIREBASE_PROJECT_ID|${{ secrets.FIREBASE_PROJECT_ID }}|g' templates/index.html
        sed -i 's|FIREBASE_STORAGE_BUCKET|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g' templates/index.html
        sed -i 's|FIREBASE_MESSAGING_SENDER_ID|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g' templates/index.html
        sed -i 's|FIREBASE_APP_ID|${{ secrets.FIREBASE_APP_ID }}|g' templates/index.html
        sed -i 's|FIREBASE_MEASUREMENT_ID|${{ secrets.FIREBASE_MEASUREMENT_ID }}|g' templates/index.html

    - name: Generate site
      run: |
        python generate.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build